python3 analyzer_normal.py root_cat2_parse.csv analyze_result.txt
python3 analyzer_normal.py first_cat1_parse.csv analyze_result.txt
python3 analyzer_normal.py first_cat2_parse.csv analyze_result.txt
python3 analyzer_normal.py first_cat3_parse.csv analyze_result.txt
python3 analyzer_normal.py first_cat4_parse.csv analyze_result.txt
python3 analyzer_normal.py first_cat5_parse.csv analyze_result.txt
python3 analyzer_normal.py first_cat6_parse.csv analyze_result.txt
python3 analyzer_normal.py first_cat7_parse.csv analyze_result.txt
python3 analyzer_normal.py second_cat1_parse.csv analyze_result.txt
python3 analyzer_normal.py second_cat2_parse.csv analyze_result.txt
python3 analyzer_normal.py second_cat3_parse.csv analyze_result.txt
python3 analyzer_normal.py second_cat4_parse.csv analyze_result.txt
python3 analyzer_normal.py second_cat5_parse.csv analyze_result.txt
python3 analyzer_normal.py second_cat6_parse.csv analyze_result.txt
python3 analyzer_normal.py second_cat7_parse.csv analyze_result.txt
python3 analyzer_normal.py third_cat1_parse_v1.csv analyze_result.txt
python3 analyzer_normal.py third_cat2_parse_v1.csv analyze_result.txt
python3 analyzer_normal.py third_cat3_parse_v1.csv analyze_result.txt
python3 analyzer_normal.py third_cat4_parse_v1.csv analyze_result.txt
python3 analyzer_normal.py third_cat5_parse_v1.csv analyze_result.txt
python3 analyzer_normal.py third_cat6_parse_v1.csv analyze_result.txt
python3 analyzer_normal.py third_cat7_parse_v1.csv analyze_result.txt