python3 analyzer.py first_cat1.csv result_analyze.txt
python3 analyzer.py first_cat2.csv result_analyze.txt
python3 analyzer.py first_cat3.csv result_analyze.txt
python3 analyzer.py first_cat4.csv result_analyze.txt
python3 analyzer.py first_cat5.csv result_analyze.txt
python3 analyzer.py first_cat6.csv result_analyze.txt
python3 analyzer.py first_cat7.csv result_analyze.txt
python3 analyzer.py second_cat1.csv result_analyze.txt
python3 analyzer.py second_cat2.csv result_analyze.txt
python3 analyzer.py second_cat3.csv result_analyze.txt
python3 analyzer.py second_cat4.csv result_analyze.txt
python3 analyzer.py second_cat5.csv result_analyze.txt
python3 analyzer.py second_cat6.csv result_analyze.txt
python3 analyzer.py second_cat7.csv result_analyze.txt
python3 analyzer.py third_cat1.csv result_analyze.txt
python3 analyzer.py third_cat2.csv result_analyze.txt
python3 analyzer.py third_cat3.csv result_analyze.txt
python3 analyzer.py third_cat4.csv result_analyze.txt
python3 analyzer.py third_cat5.csv result_analyze.txt
python3 analyzer.py third_cat6.csv result_analyze.txt
python3 analyzer.py third_cat7.csv result_analyze.txt